# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2455fabba922a5c8387cea426edc5dfd98a815d503d863dbceb4aceb4356460ad799581b631fe69fab9363ab75f3f717afb1f8934d2680aa0c962645b39ed3ee

test:
  secret_key_base: 12082af7ecb68f7eab30d15a34899e993db5ff784655101cf7843611e3d946ab5b7e0e53062ac3dbbcf75f414c0bc9e56ac5acfdd31d772f405f6427439ce508

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
